### PR TITLE
Fixed some misspelings

### PR DESCRIPTION
**Pull request by Zaikonurami**
## Details

This Pull Request fixes typos or mistakes in Spanish

### CODE REVIEW

**Comment by EcoScratcher** [comment]
I am being rather pedantic here but the diff seems to be abit glitchy so it would be nice to list the changes that you have made between this PR and the last one.

See #2  for an example

**Comment by Zaikonurami** [comment]
the problem is, I fixed all the file

**Comment by EcoScratcher** [comment]
> the problem is, I fixed all the file

I think what I meant is to *note* the fixes that you made to the file (i.e. note down the error and what you changed it to such that the error is fixed/removed)

**Comment by juliaoverflow** [comment]
fixed merge conflict, and i've also made it so `// Translated by: ` comments persist when syncing

**Pull request merged**
